import Link from "next/link";
import { redirect } from "next/navigation";
import { createClient } from "@/lib/supabase/server";
import { CompetitionService } from "@/services/competition.service";
import {
  attachCompetitionTournament, changeCompetitionEventStatus, changeCompetitionTournamentStatus, createCompetitionActivity, createCompetitionEvent,
  deleteCompetitionEvent, inviteCompetitionClub, moveCompetitionActivity, recordCompetitionDelay,
  updateCompetitionActivityDependency, updateCompetitionEvent, linkCompetitionParticipantProfile,
} from "./actions";

const panel = "rounded-xl border border-cyan-400/25 bg-black/60 p-5";
const input = "w-full rounded border border-gray-600 bg-black px-3 py-2 text-sm text-white";
const formatInput = (value: string) => new Date(value).toISOString().slice(0, 16);

export default async function CompetitionsAdminPage() {
  const client = await createClient();
  const service = new CompetitionService(client);
  try { await service.requireAdmin(); } catch { redirect("/archives"); }
  const data = await service.adminDashboard();
  const tournamentById = new Map(data.tournaments.map((item) => [item.id, item]));
  const clubById = new Map(data.clubs.map((item) => [item.id, item]));
  const accessByParticipant = new Map(data.accesses.map((item) => [item.participant_id, item.public_token]));

  return <main className="mx-auto min-h-screen max-w-7xl space-y-7 p-6 text-white">
    <header className="flex flex-wrap items-center justify-between gap-3"><div><h1 className="text-3xl font-bold text-cyan-300">Compétitions</h1><p className="text-sm text-gray-400">Événements, tournois, planning dynamique et accès participants</p></div><Link href="/archives" className="text-cyan-300">← Archives</Link></header>

    <section className={panel}><h2 className="mb-4 text-xl font-bold text-purple-300">Créer un événement</h2><form action={createCompetitionEvent} className="grid gap-3 md:grid-cols-2">
      <input className={input} name="name" minLength={2} maxLength={160} placeholder="Nom" required/><input className={input} name="location" placeholder="Lieu" required/>
      <input className={input} name="startsAt" type="datetime-local" required/><input className={input} name="disciplines" placeholder="Disciplines séparées par des virgules"/>
      <input className={input} name="logoPath" placeholder="Chemin du logo"/><input className={input} name="imagePath" placeholder="Chemin de l’image"/>
      <textarea className={`${input} md:col-span-2`} name="description" maxLength={4000} placeholder="Description" rows={3}/><button className="rounded bg-purple-700 px-4 py-2 font-bold md:col-span-2">Créer</button>
    </form></section>

    {data.events.map((event) => { const activities = data.activities.filter((item) => item.event_id === event.id); const links = data.links.filter((item) => item.event_id === event.id); const linkedIds = new Set(links.map((item) => item.tournament_id)); const participants = data.participants.filter((item) => linkedIds.has(item.tournament_id)); return <section key={event.id} className={`${panel} space-y-5`}>
      <div className="flex flex-wrap justify-between gap-3"><div><h2 className="text-2xl font-bold text-yellow-300">{event.name}</h2><p className="text-sm text-gray-400">{event.location} · {new Date(event.starts_at).toLocaleString("fr-FR")} · {event.status}</p></div><div className="flex flex-wrap gap-2">{(["draft","published","active","completed","cancelled"] as const).map((status) => <form action={changeCompetitionEventStatus} key={status}><input type="hidden" name="eventId" value={event.id}/><input type="hidden" name="status" value={status}/><button disabled={event.status === status} className="rounded border border-gray-600 px-2 py-1 text-xs disabled:opacity-30">{status}</button></form>)}<form action={deleteCompetitionEvent}><input type="hidden" name="eventId" value={event.id}/><button className="rounded border border-red-500 px-2 py-1 text-xs text-red-300">Supprimer</button></form></div></div>

      <details><summary className="cursor-pointer font-bold text-cyan-300">Modifier l’événement</summary><form action={updateCompetitionEvent} className="mt-3 grid gap-2 md:grid-cols-2"><input type="hidden" name="eventId" value={event.id}/><input className={input} name="name" defaultValue={event.name} required/><input className={input} name="location" defaultValue={event.location} required/><input className={input} name="startsAt" type="datetime-local" defaultValue={formatInput(event.starts_at)} required/><input className={input} name="disciplines" defaultValue={event.disciplines.join(", ")}/><input className={input} name="logoPath" defaultValue={event.logo_path ?? ""}/><input className={input} name="imagePath" defaultValue={event.image_path ?? ""}/><textarea className={`${input} md:col-span-2`} name="description" defaultValue={event.description ?? ""}/><button className="rounded bg-cyan-700 p-2 md:col-span-2">Enregistrer</button></form></details>

      <div className="grid gap-5 lg:grid-cols-2"><div><h3 className="mb-2 font-bold text-green-300">Tournois et clubs invités</h3><form action={attachCompetitionTournament} className="mb-2 flex gap-2"><input type="hidden" name="eventId" value={event.id}/><select className={input} name="tournamentId" required><option value="">Tournoi…</option>{data.tournaments.map((tournament) => <option key={tournament.id} value={tournament.id}>{tournament.name}</option>)}</select><input name="sortOrder" type="number" min={0} defaultValue={links.length} className="w-20 rounded bg-black px-2"/><button className="rounded bg-green-700 px-3">Lier</button></form><div className="mb-3 space-y-2">{links.map((link) => { const tournament = tournamentById.get(link.tournament_id); return <div key={link.tournament_id} className="flex flex-wrap items-center justify-between rounded border border-gray-700 p-2 text-sm"><span>{tournament?.name} · {tournament?.status}</span><div className="flex gap-1">{(["active","completed"] as const).map((status) => <form action={changeCompetitionTournamentStatus} key={status}><input type="hidden" name="tournamentId" value={link.tournament_id}/><input type="hidden" name="status" value={status}/><button className="rounded border px-2 py-1 text-xs">{status === "active" ? "Lancer" : "Terminer / publier"}</button></form>)}</div></div>; })}{!links.length && <p className="text-gray-400">Aucun tournoi</p>}</div><form action={inviteCompetitionClub} className="flex gap-2"><input type="hidden" name="eventId" value={event.id}/><select className={input} name="clubId" required><option value="">Club…</option>{data.clubs.map((club) => <option key={club.id} value={club.id}>{club.name}</option>)}</select><button className="rounded bg-green-700 px-3">Inviter</button></form><p className="mt-2 text-sm text-gray-300">{data.invitedClubs.filter((item) => item.event_id === event.id).map((item) => clubById.get(item.club_id)?.name).filter(Boolean).join(" · ") || "Aucun club"}</p></div>

      <div><h3 className="mb-2 font-bold text-orange-300">Ajouter un atelier</h3><form action={createCompetitionActivity} className="grid gap-2 sm:grid-cols-2"><input type="hidden" name="eventId" value={event.id}/><input className={input} name="name" placeholder="Nom" required/><input className={input} name="durationMinutes" type="number" min={1} max={1440} placeholder="Durée (min)" required/><select className={input} name="scheduleMode"><option value="fixed">Heure fixe</option><option value="after_previous">Après l’atelier précédent</option></select><input className={input} name="plannedStartAt" type="datetime-local" defaultValue={formatInput(event.starts_at)}/><select className={input} name="previousActivityId"><option value="">Atelier précédent…</option>{activities.map((activity) => <option key={activity.id} value={activity.id}>{activity.name}</option>)}</select><select className={input} name="tournamentId"><option value="">Activité générale</option>{links.map((link) => <option key={link.tournament_id} value={link.tournament_id}>{tournamentById.get(link.tournament_id)?.name}</option>)}</select><input className={input} name="room" placeholder="Salle"/><input className={input} name="tatami" placeholder="Tatami"/><input className={input} name="managerName" placeholder="Responsable"/><input className={input} name="position" type="number" min={1} defaultValue={activities.length + 1} required/><textarea className={`${input} sm:col-span-2`} name="description" placeholder="Description"/><button className="rounded bg-orange-700 p-2 sm:col-span-2">Ajouter</button></form></div></div>

      <div><h3 className="mb-3 font-bold text-blue-300">Planning dynamique</h3><div className="space-y-3">{activities.map((activity) => { const delay = activity.actual_started_at ? Math.max(0, Math.round((new Date(activity.actual_started_at).getTime() - new Date(activity.estimated_start_at).getTime()) / 60000)) : Math.max(0, Math.round((Date.now() - new Date(activity.estimated_start_at).getTime()) / 60000)); return <div key={activity.id} className="rounded border border-gray-700 p-3"><div className="flex flex-wrap items-center justify-between gap-2"><div><p className="font-bold">{activity.position}. {activity.name}</p><p className="text-xs text-gray-400">{new Date(activity.estimated_start_at).toLocaleString("fr-FR")} · {activity.duration_minutes} min · {activity.room ?? "—"} · Tatami {activity.tatami ?? "—"}</p>{delay > 0 && !activity.actual_ended_at && <p className="text-xs text-red-300">Retard estimé : {delay} min</p>}</div><div className="flex gap-1"><form action={recordCompetitionDelay}><input type="hidden" name="activityId" value={activity.id}/><input type="hidden" name="timingAction" value="start"/><button className="rounded border px-2 py-1 text-xs">Démarrer</button></form><form action={recordCompetitionDelay}><input type="hidden" name="activityId" value={activity.id}/><input type="hidden" name="timingAction" value="finish"/><button className="rounded border px-2 py-1 text-xs">Terminer</button></form></div></div><div className="mt-2 grid gap-2 sm:grid-cols-2"><form action={moveCompetitionActivity} className="flex gap-2"><input type="hidden" name="activityId" value={activity.id}/><input className={input} name="position" type="number" min={1} defaultValue={activity.position}/><button className="rounded border px-2">Déplacer</button></form><form action={updateCompetitionActivityDependency} className="grid grid-cols-2 gap-2"><input type="hidden" name="activityId" value={activity.id}/><input type="hidden" name="eventId" value={event.id}/><select className={input} name="scheduleMode" defaultValue={activity.schedule_mode}><option value="fixed">Fixe</option><option value="after_previous">Dépendant</option></select><input className={input} name="plannedStartAt" type="datetime-local" defaultValue={activity.planned_start_at ? formatInput(activity.planned_start_at) : formatInput(event.starts_at)}/><select className={`${input} col-span-2`} name="previousActivityId" defaultValue={activity.previous_activity_id ?? ""}><option value="">Précédent…</option>{activities.filter((candidate) => candidate.position < activity.position).map((candidate) => <option key={candidate.id} value={candidate.id}>{candidate.name}</option>)}</select><button className="rounded border px-2 col-span-2">Modifier la dépendance</button></form></div></div>; })}</div></div>

      <div><h3 className="mb-2 font-bold text-pink-300">Accès participants</h3><div className="grid gap-2 sm:grid-cols-2 lg:grid-cols-3">{participants.map((participant) => { const token = accessByParticipant.get(participant.id); return <div key={participant.id} className="rounded border border-pink-400/30 p-2 text-sm">{token ? <Link href={`/competition/p/${token}`} className="font-bold text-pink-300 hover:underline">{participant.display_name_snapshot} · {tournamentById.get(participant.tournament_id)?.name}</Link> : <p>{participant.display_name_snapshot}</p>}<form action={linkCompetitionParticipantProfile} className="mt-2 flex gap-1"><input type="hidden" name="participantId" value={participant.id}/><select name="userId" className={input} defaultValue={participant.user_id ?? ""}><option value="">Aucun profil lié</option>{data.profiles.map((profile) => <option key={profile.id} value={profile.id}>{profile.display_name}</option>)}</select><button className="rounded border px-2">Lier</button></form></div>; })}</div></div>
    </section>; })}
  </main>;
}
